name: Update M3U Playlist

on:
  push:
    paths:
      - playlist.m3u  # Trigger the action when playlist.m3u is updated
  workflow_dispatch: # Allow manual runs

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python Script
        run: python update_playlist.py

      - name: Commit Updated Playlist
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add updated_playlist.m3u
          git commit -m "Update playlist with TVG logos"
          git push
